# Generated by Django 2.1.7 on 2019-03-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
