# Generated by Django 2.1.7 on 2019-03-10 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comunicaciones', '0002_auto_20190310_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
