# Generated by Django 2.1.7 on 2019-03-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunicaciones', '0003_remove_post_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ddbb25',
            fields=[
                ('id', models.FloatField(db_column='Número', primary_key=True, serialize=False)),
                ('posición_anterior', models.CharField(blank=True, db_column='Posición anterior', max_length=255, null=True)),
                ('posición_nueva', models.CharField(blank=True, db_column='Posición Nueva', max_length=255, null=True)),
                ('isla', models.CharField(blank=True, db_column='ISLA', max_length=255, null=True)),
                ('devol', models.FloatField(blank=True, db_column='DEVOL', null=True)),
                ('hold', models.FloatField(blank=True, db_column='HOLD', null=True)),
                ('accion', models.CharField(blank=True, db_column='ACCION', max_length=255, null=True)),
                ('sala_anterior', models.CharField(blank=True, db_column='Sala anterior', max_length=255, null=True)),
                ('sala_nueva', models.CharField(blank=True, db_column='Sala Nueva', max_length=255, null=True)),
                ('fabricante', models.CharField(blank=True, db_column='Fabricante', max_length=255, null=True)),
                ('modelo', models.CharField(blank=True, db_column='Modelo', max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=255, null=True)),
                ('año_fab', models.FloatField(blank=True, db_column='Año Fab', null=True)),
                ('juego', models.CharField(blank=True, db_column='Juego', max_length=255, null=True)),
                ('denom_anterior', models.CharField(blank=True, db_column='Denom Anterior', max_length=255, null=True)),
                ('denom_nueva', models.CharField(blank=True, db_column='Denom Nueva', max_length=255, null=True)),
                ('progresivo', models.CharField(blank=True, db_column='Progresivo', max_length=255, null=True)),
                ('participacion', models.CharField(blank=True, db_column='Participacion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'DDBB25',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tdatos',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('field_date', models.DateTimeField(blank=True, db_column='_DATE', null=True)),
                ('field_slot', models.IntegerField(blank=True, db_column='_SLOT', null=True)),
                ('field_model', models.CharField(blank=True, db_column='_MODEL', max_length=150, null=True)),
                ('field_denom', models.FloatField(blank=True, db_column='_DENOM', null=True)),
                ('field_devol', models.FloatField(blank=True, db_column='_DEVOL', null=True)),
                ('field_in', models.FloatField(blank=True, db_column='_IN', null=True)),
                ('field_out', models.FloatField(blank=True, db_column='_OUT', null=True)),
                ('field_hp', models.FloatField(blank=True, db_column='_HP', null=True)),
                ('field_drop', models.FloatField(blank=True, db_column='_DROP', null=True)),
                ('field_games', models.FloatField(blank=True, db_column='_GAMES', null=True)),
                ('field_bill', models.FloatField(blank=True, db_column='_BILL', null=True)),
                ('field_jp', models.FloatField(blank=True, db_column='_JP', null=True)),
                ('field_win', models.FloatField(blank=True, db_column='_WIN', null=True)),
                ('field_sala', models.CharField(blank=True, db_column='_SALA', max_length=255, null=True)),
            ],
            options={
                'db_table': 'TDATOS',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
