# Generated by Django 2.2.6 on 2019-10-05 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comunicaciones', '0005_auto_20190311_1626'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ddbb25',
        ),
        migrations.DeleteModel(
            name='Tdatos',
        ),
    ]
