# Generated by Django 2.1.7 on 2019-03-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbTemperatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpi', models.CharField(db_column='RPi', max_length=32)),
                ('temperatura', models.IntegerField(blank=True, db_column='Temperatura', null=True)),
                ('humedad', models.IntegerField(blank=True, db_column='Humedad', null=True)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
            ],
            options={
                'db_table': 'tb_temperatura',
                'managed': False,
            },
        ),
    ]
